services:
  web:
    image: caddy:2.7.5-alpine
    container_name: btc-premium-calc
    restart: unless-stopped
    ports:
      - "8443:443"  # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./:/usr/share/caddy/
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
